services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=project_management_db'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
      - 'SPRING_JPA_HIBERNATE_DDL_AUTO=update'
    ports:
      - '5432:5432'
